name: Scoreboard
version: '${project.version}'
main: net.juligames.core.addons.scoreboard.ScoreboardPlugin
api-version: 1.18
author: Ture Bentzin
depend: [ PaperCore ]
commands:
  update:
    description: test cmd
